export default {
  name: 'phoneacc',
  title: 'Accessory',
  type: 'document',
  icon: () => '🎧',
  groups: [
    { name: 'colorVariants', title: 'Colors & Variant Images' },
    { name: 'shipping', title: 'Shipping Information' },
  ],
  fields: [
    {
      name: 'image',
      title: 'Main Image',
      type: 'array',
      of: [{ type: 'image' }],
      options: { hotspot: true },
    },
    {
      name: 'image2',
      title: 'Image 2',
      type: 'array',
      of: [{ type: 'image' }],
      options: { hotspot: true },
    },
    {
      name: 'image3',
      title: 'Image 3',
      type: 'array',
      of: [{ type: 'image' }],
      options: { hotspot: true },
    },
    {
      name: 'image4',
      title: 'Image 4',
      type: 'array',
      of: [{ type: 'image' }],
      options: { hotspot: true },
    },
    {
      name: 'image5',
      title: 'Image 5',
      type: 'array',
      of: [{ type: 'image' }],
      options: { hotspot: true },
    },
    {
      name: 'image6',
      title: 'Image 6',
      type: 'array',
      of: [{ type: 'image' }],
      options: { hotspot: true },
    },
    {
      name: 'imagecolour',
      title: 'Color Variant Images – Color 1',
      type: 'array',
      group: 'colorVariants',
      of: [{ type: 'image' }],
      options: { hotspot: true },
    },
    {
      name: 'imagecolour2',
      title: 'Color Variant Images – Color 2',
      type: 'array',
      group: 'colorVariants',
      of: [{ type: 'image' }],
      options: { hotspot: true },
    },
    {
      name: 'imagecolour3',
      title: 'Color Variant Images – Color 3',
      type: 'array',
      group: 'colorVariants',
      of: [{ type: 'image' }],
      options: { hotspot: true },
    },
    {
      name: 'imagecolour4',
      title: 'Color Variant Images – Color 4',
      type: 'array',
      group: 'colorVariants',
      of: [{ type: 'image' }],
      options: { hotspot: true },
    },
    {
      name: 'imagecolour5',
      title: 'Color Variant Images – Color 5',
      type: 'array',
      group: 'colorVariants',
      of: [{ type: 'image' }],
      options: { hotspot: true },
    },
    {
      name: 'imagecolour6',
      title: 'Color Variant Images – Color 6',
      type: 'array',
      group: 'colorVariants',
      of: [{ type: 'image' }],
      options: { hotspot: true },
    },
    {
      name: 'imagecolour7',
      title: 'Color Variant Images – Color 7',
      type: 'array',
      group: 'colorVariants',
      of: [{ type: 'image' }],
      options: { hotspot: true },
    },
    {
      name: 'imagecolour8',
      title: 'Color Variant Images – Color 8',
      type: 'array',
      group: 'colorVariants',
      of: [{ type: 'image' }],
      options: { hotspot: true },
    },
    {
      name: 'imagecolour9',
      title: 'Color Variant Images – Color 9',
      type: 'array',
      group: 'colorVariants',
      of: [{ type: 'image' }],
      options: { hotspot: true },
    },
    {
      name: 'youtubeLink',
      title: 'YouTube Link',
      type: 'string',
    },
    {
      name: 'name',
      title: 'Name',
      type: 'string',
    },
    {
      name: 'imageAlt',
      title: 'Image SEO Description',
      type: 'string',
    },
    {
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: {
        source: 'name',
        maxLength: 90,
      },
    },
    {
      name: 'price',
      title: 'Price',
      type: 'number',
    },
    {
      name: 'originalPrice',
      title: 'Original Price',
      type: 'number',
      description: 'Original price before discount',
    },
    {
      name: 'details',
      title: 'Product Details',
      type: 'text',
      description: 'Detailed accessory description',
    },
    {
      name: 'brand',
      title: 'Brand',
      type: 'string',
    },
    {
      name: 'accessoryType',
      title: 'Accessory Type',
      type: 'string',
      options: {
        list: [
          { title: 'Phone Case', value: 'case' },
          { title: 'Screen Protector', value: 'screen-protector' },
          { title: 'Charger', value: 'charger' },
          { title: 'Cable', value: 'cable' },
          { title: 'Earbuds / Headphones', value: 'earbuds' },
          { title: 'Power Bank', value: 'power-bank' },
          { title: 'Car Mount', value: 'car-mount' },
          { title: 'Stylus', value: 'stylus' },
          { title: 'Holder / Stand', value: 'holder' },
          { title: 'Memory Card', value: 'memory-card' },
          { title: 'Smartwatch', value: 'smartwatch' },
          { title: 'Other', value: 'other' },
        ]
      }
    },
    {
      name: 'compatibleDevices',
      title: 'Compatible Devices',
      type: 'array',
      of: [{ type: 'string' }],
      description: 'List of compatible device names (e.g., DOOGEE V Max, iPhone 15)',
    },
    {
      name: 'material',
      title: 'Material',
      type: 'string',
      description: 'e.g., Silicone, Tempered Glass, Leather, TPU',
    },
    {
      name: 'colors',
      title: 'Available Colors',
      type: 'array',
      group: 'colorVariants',
      of: [
        {
          type: 'object',
          fields: [
            {
              name: 'name',
              title: 'Color Name',
              type: 'string',
              description: 'e.g., Midnight Black, Forest Green',
            },
            {
              name: 'hex',
              title: 'Hex Code',
              type: 'string',
              description: 'e.g., #FF0000, #1A1A2E',
            },
          ],
          preview: {
            select: { title: 'name', subtitle: 'hex' },
          },
        },
      ],
    },
    {
      name: 'connectivity',
      title: 'Connectivity',
      type: 'string',
      description: 'e.g., Bluetooth 5.3, USB-C, Lightning',
    },
    {
      name: 'weight',
      title: 'Weight',
      type: 'string',
      description: 'e.g., 50g, 200g',
    },
    {
      name: 'dimensions',
      title: 'Dimensions',
      type: 'string',
      description: 'e.g., 15cm x 7cm x 1.2cm',
    },
    {
      name: 'warranty',
      title: 'Warranty',
      type: 'string',
    },
    {
      name: 'whatsInTheBox',
      title: "What's In The Box",
      type: 'array',
      of: [{ type: 'string' }],
      description: 'Items included (e.g., 1x Device, USB-C Cable, Charger, Manual)',
    },
    {
      name: 'keywoards',
      title: 'Keywords',
      type: 'text',
      of: [{ type: 'string' }],
      description: 'Enter keywords for better searchability',
    },
    {
      name: 'id',
      title: 'Id',
      type: 'string',
    },
    {
      name: 'stockQuantity',
      title: 'Stock Quantity',
      type: 'number',
    },
    {
      name: 'inStock',
      title: 'In Stock',
      type: 'boolean',
      initialValue: true,
    },
    {
      name: 'featured',
      title: 'Featured',
      type: 'boolean',
      initialValue: false,
    },
    {
      name: 'onSale',
      title: 'On Sale',
      type: 'boolean',
      initialValue: false,
    },
    {
      name: 'subsubcategory',
      title: 'SubsubCategory',
      type: 'string',
    },
    {
      name: 'location',
      title: 'Item Location',
      type: 'string',
      options: {
        list: [
          { title: 'HONG KONG Warehouse', value: 'HK Warehouse' },
          { title: 'TTD Warehouse', value: 'TT Warehouse' },
          { title: 'USA Warehouse', value: 'USA Warehouse' },
          { title: 'WorldWide Shipping', value: 'WorldWide Shipping' },
        ],
      },
    },
    {
      name: 'shippingWeightKg',
      title: 'Shipping Weight (kg)',
      type: 'number',
      description: 'Package weight in kilograms for shipping calculation',
      group: 'shipping',
    },
    {
      name: 'shippingLengthCm',
      title: 'Package Length (cm)',
      type: 'number',
      description: 'Package length in centimeters',
      group: 'shipping',
    },
    {
      name: 'shippingWidthCm',
      title: 'Package Width (cm)',
      type: 'number',
      description: 'Package width in centimeters',
      group: 'shipping',
    },
    {
      name: 'shippingHeightCm',
      title: 'Package Height (cm)',
      type: 'number',
      description: 'Package height in centimeters',
      group: 'shipping',
    },
  ],
  preview: {
    select: {
      title: 'name',
      subtitle: 'accessoryType',
      media: 'image.0',
    },
    prepare(selection) {
      const { title, subtitle, media } = selection;
      return {
        title: title,
        subtitle: subtitle || 'Accessory',
        media: media,
      };
    },
  },
}
