export default {
  name: 'product',
  title: 'Rugged Device',
  type: 'document',
  icon: () => '🛡️',
  groups: [
    { name: 'colorVariants', title: 'Colors & Variant Images' },
    { name: 'shipping', title: 'Shipping Information' },
  ],
  fields: [
    {
      name: 'image',
      title: 'Main Image',
      type: 'array',
      of: [{ type: 'image' }],
      options: { hotspot: true },
    },
    {
      name: 'image2',
      title: 'Image 2',
      type: 'array',
      of: [{ type: 'image' }],
      options: { hotspot: true },
    },
    {
      name: 'image3',
      title: 'Image 3',
      type: 'array',
      of: [{ type: 'image' }],
      options: { hotspot: true },
    },
    {
      name: 'image4',
      title: 'Image 4',
      type: 'array',
      of: [{ type: 'image' }],
      options: { hotspot: true },
    },
    {
      name: 'image5',
      title: 'Image 5',
      type: 'array',
      of: [{ type: 'image' }],
      options: { hotspot: true },
    },
    {
      name: 'image6',
      title: 'Image 6',
      type: 'array',
      of: [{ type: 'image' }],
      options: { hotspot: true },
    },
    {
      name: 'imagecolour',
      title: 'Color Variant Images – Color 1',
      type: 'array',
      group: 'colorVariants',
      of: [{ type: 'image' }],
      options: { hotspot: true },
    },
    {
      name: 'imagecolour2',
      title: 'Color Variant Images – Color 2',
      type: 'array',
      group: 'colorVariants',
      of: [{ type: 'image' }],
      options: { hotspot: true },
    },
    {
      name: 'imagecolour3',
      title: 'Color Variant Images – Color 3',
      type: 'array',
      group: 'colorVariants',
      of: [{ type: 'image' }],
      options: { hotspot: true },
    },
    {
      name: 'imagecolour4',
      title: 'Color Variant Images – Color 4',
      type: 'array',
      group: 'colorVariants',
      of: [{ type: 'image' }],
      options: { hotspot: true },
    },
    {
      name: 'imagecolour5',
      title: 'Color Variant Images – Color 5',
      type: 'array',
      group: 'colorVariants',
      of: [{ type: 'image' }],
      options: { hotspot: true },
    },
    {
      name: 'imagecolour6',
      title: 'Color Variant Images – Color 6',
      type: 'array',
      group: 'colorVariants',
      of: [{ type: 'image' }],
      options: { hotspot: true },
    },
    {
      name: 'imagecolour7',
      title: 'Color Variant Images – Color 7',
      type: 'array',
      group: 'colorVariants',
      of: [{ type: 'image' }],
      options: { hotspot: true },
    },
    {
      name: 'imagecolour8',
      title: 'Color Variant Images – Color 8',
      type: 'array',
      group: 'colorVariants',
      of: [{ type: 'image' }],
      options: { hotspot: true },
    },
    {
      name: 'imagecolour9',
      title: 'Color Variant Images – Color 9',
      type: 'array',
      group: 'colorVariants',
      of: [{ type: 'image' }],
      options: { hotspot: true },
    },
    {
      name: 'youtubeLink',
      title: 'YouTube Link',
      type: 'string',
    },
    {
      name: 'name',
      title: 'Name',
      type: 'string',
    },
    {
      name: 'imageAlt',
      title: 'Image SEO Description',
      type: 'string',
      description: 'Alt text for images (auto-generated from product name if left empty).',
    },
    {
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: {
        source: 'name',
        maxLength: 90,
      },
    },
    {
      name: 'price',
      title: 'Price',
      type: 'number',
    },
    {
      name: 'details',
      title: 'Product Details',
      type: 'text',
      description: 'Detailed product description with key features',
    },
    {
      name: 'brand',
      title: 'Brand',
      type: 'string',
    },
    {
      name: 'protectionRating',
      title: 'Protection Rating',
      type: 'string',
      options: {
        list: [
          { title: 'IP68', value: 'ip68' },
          { title: 'IP69K', value: 'ip69k' },
          { title: 'MIL-STD-810G', value: 'mil-std' },
          { title: 'MIL-STD-810H', value: 'mil-std-810h' },
          { title: 'IP68 + MIL-STD-810G', value: 'ip68-mil-std' },
          { title: 'IP69K + MIL-STD-810H', value: 'ip69k-mil-std-810h' },
        ]
      }
    },
    {
      name: 'screenSize',
      title: 'Screen Size',
      type: 'string',
      description: 'e.g., 6.58", 6.78", 10.1"',
    },
    {
      name: 'screenResolution',
      title: 'Screen Resolution',
      type: 'string',
      description: 'e.g., 2408 x 1080 FHD+',
    },
    {
      name: 'mainCamera',
      title: 'Main Camera (MP)',
      type: 'string',
      description: 'e.g., 200MP, 108MP, 64MP',
    },
    {
      name: 'frontCamera',
      title: 'Front Camera (MP)',
      type: 'string',
      description: 'e.g., 32MP, 16MP',
    },
    {
      name: 'nightVisionCamera',
      title: 'Night Vision Camera (MP)',
      type: 'string',
      description: 'e.g., 20MP Night Vision',
    },
    {
      name: 'battery',
      title: 'Battery Capacity (mAh)',
      type: 'string',
      description: 'e.g., 20500mAh, 10000mAh',
    },
    {
      name: 'chargingSpeed',
      title: 'Charging Speed',
      type: 'string',
      description: 'e.g., 45W Fast Charging, 33W',
    },
    {
      name: 'processor',
      title: 'Processor',
      type: 'string',
      description: 'e.g., MediaTek Dimensity 7300 5G Octa-Core',
    },
    {
      name: 'osVersion',
      title: 'Operating System',
      type: 'string',
      description: 'e.g., Android 14, Android 15',
    },
    {
      name: 'connectivity5G',
      title: '5G Support',
      type: 'boolean',
      initialValue: false,
    },
    {
      name: 'nfc',
      title: 'NFC Support',
      type: 'boolean',
      initialValue: false,
    },
    {
      name: 'features',
      title: 'Special Features',
      type: 'array',
      of: [{ type: 'string' }],
      options: {
        list: [
          { title: 'Thermal/Infrared Camera', value: 'thermal-infrared' },
          { title: 'Night Vision', value: 'night-vision' },
          { title: 'FLIR', value: 'flir' },
          { title: 'Projector', value: 'projector' },
          { title: 'Dual Camping Lights', value: 'camping-lights' },
          { title: 'Laser Rangefinder', value: 'laser-rangefinder' },
          { title: 'Walkie-Talkie', value: 'walkie-talkie' },
          { title: 'Fingerprint Scanner', value: 'fingerprint' },
          { title: 'Face Unlock', value: 'face-unlock' },
          { title: 'Wireless Charging', value: 'wireless-charging' },
          { title: 'Reverse Charging', value: 'reverse-charging' },
          { title: 'Underwater Camera', value: 'underwater-camera' },
          { title: 'Barometer', value: 'barometer' },
          { title: 'FM Radio', value: 'fm-radio' },
        ]
      }
    },
    {
      name: 'featureHighlights',
      title: 'Feature Highlights',
      type: 'array',
      of: [{
        type: 'object',
        fields: [
          { name: 'title', title: 'Highlight Title', type: 'string', description: 'e.g., 20,500mAh' },
          { name: 'subtitle', title: 'Subtitle', type: 'string', description: 'e.g., Mega Battery' },
          { name: 'image', title: 'Highlight Image', type: 'image', options: { hotspot: true } },
        ]
      }],
      description: 'Visual feature highlights grid (like battery, camera, projector sections)',
    },
    {
      name: 'dimensions',
      title: 'Dimensions',
      type: 'string',
      description: 'e.g., 178.6 x 82.8 x 15.5mm',
    },
    {
      name: 'weight',
      title: 'Weight',
      type: 'string',
      description: 'e.g., 398g',
    },
    {
      name: 'simType',
      title: 'SIM Type',
      type: 'string',
      description: 'e.g., Dual Nano SIM',
    },
    {
      name: 'networkBands',
      title: 'Network Bands',
      type: 'text',
      description: 'Supported network bands (2G/3G/4G/5G)',
    },
    {
      name: 'wifi',
      title: 'WiFi',
      type: 'string',
      description: 'e.g., WiFi 6, 802.11 a/b/g/n/ac/ax',
    },
    {
      name: 'bluetooth',
      title: 'Bluetooth',
      type: 'string',
      description: 'e.g., Bluetooth 5.3',
    },
    {
      name: 'sensors',
      title: 'Sensors',
      type: 'text',
      description: 'List of sensors (Gyroscope, Accelerometer, etc.)',
    },
    {
      name: 'id',
      title: 'Id',
      type: 'string',
    },
    {
      name: 'keywoards',
      title: 'Keywords',
      type: 'text',
      description: 'Enter keywords for better searchability',
    },
    {
      name: 'ram',
      title: 'RAM',
      type: 'string',
      options: {
        list: [
          { title: '2GB', value: '2GB' },
          { title: '4GB', value: '4GB' },
          { title: '6GB', value: '6GB' },
          { title: '8GB', value: '8GB' },
          { title: '12GB', value: '12GB' },
          { title: '16GB', value: '16GB' },
          { title: '24GB', value: '24GB' },
        ],
      },
    },
    {
      name: 'rom',
      title: 'ROM / Storage',
      type: 'string',
      options: {
        list: [
          { title: '32GB', value: '32GB' },
          { title: '64GB', value: '64GB' },
          { title: '128GB', value: '128GB' },
          { title: '256GB', value: '256GB' },
          { title: '512GB', value: '512GB' },
          { title: '1TB', value: '1TB' },
        ],
      },
    },
    {
      name: 'expandableStorage',
      title: 'Expandable Storage',
      type: 'string',
      description: 'e.g., Up to 2TB via MicroSD',
    },
    {
      name: 'colors',
      title: 'Available Colors',
      type: 'array',
      group: 'colorVariants',
      of: [
        {
          type: 'object',
          fields: [
            {
              name: 'name',
              title: 'Color Name',
              type: 'string',
              description: 'e.g., Midnight Black, Forest Green',
            },
            {
              name: 'hex',
              title: 'Hex Code',
              type: 'string',
              description: 'e.g., #FF0000, #1A1A2E',
            },
          ],
          preview: {
            select: { title: 'name', subtitle: 'hex' },
          },
        },
      ],
    },
    {
      name: 'stockQuantity',
      title: 'Stock Quantity',
      type: 'number',
    },
    {
      name: 'location',
      title: 'Item Location',
      type: 'string',
      options: {
        list: [
          { title: 'HONG KONG Warehouse', value: 'HK Warehouse' },
          { title: 'TTD Warehouse', value: 'TT Warehouse' },
          { title: 'USA Warehouse', value: 'USA Warehouse' },
          { title: 'WorldWide Shipping', value: 'WorldWide Shipping' },
        ],
      },
    },
    {
      name: 'categories',
      title: 'Categories',
      type: 'string',
    },
    {
      name: 'subcategories',
      title: 'Subcategories',
      type: 'array',
      of: [{ type: 'string' }],
    },
    {
      name: 'subsubcategories',
      title: 'Sub-subcategories',
      type: 'array',
      of: [{ type: 'string' }],
    },
    {
      name: 'originalPrice',
      title: 'Original Price',
      type: 'number',
      description: 'Original price before discount (leave empty if no discount)',
    },
    {
      name: 'featured',
      title: 'Featured',
      type: 'boolean',
      initialValue: false,
    },
    {
      name: 'onSale',
      title: 'On Sale',
      type: 'boolean',
      initialValue: false,
    },
    {
      name: 'inStock',
      title: 'In Stock',
      type: 'boolean',
      initialValue: true,
    },
    {
      name: 'warranty',
      title: 'Warranty',
      type: 'string',
      description: 'e.g., 1 Year Manufacturer Warranty',
    },
    {
      name: 'whatsInTheBox',
      title: "What's In The Box",
      type: 'array',
      of: [{ type: 'string' }],
      description: 'Items included (Phone, Charger, USB Cable, etc.)',
    },
    {
      name: 'shippingWeightKg',
      title: 'Shipping Weight (kg)',
      type: 'number',
      description: 'Package weight in kilograms for shipping calculation',
      group: 'shipping',
    },
    {
      name: 'shippingLengthCm',
      title: 'Package Length (cm)',
      type: 'number',
      description: 'Package length in centimeters',
      group: 'shipping',
    },
    {
      name: 'shippingWidthCm',
      title: 'Package Width (cm)',
      type: 'number',
      description: 'Package width in centimeters',
      group: 'shipping',
    },
    {
      name: 'shippingHeightCm',
      title: 'Package Height (cm)',
      type: 'number',
      description: 'Package height in centimeters',
      group: 'shipping',
    },
  ],
  preview: {
    select: {
      title: 'name',
      subtitle: 'brand',
      media: 'image.0',
    },
    prepare(selection) {
      const { title, subtitle, media } = selection;
      return {
        title: title,
        subtitle: subtitle ? `${subtitle}` : 'Rugged Device',
        media: media,
      };
    },
  },
}
